runtime: custom
env: flex
manual_scaling:
  instances: 1
# resources:
#   cpu: 1
#   memory_gb: 1.5
#   disk_size_gb: 10
handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist
    http_headers:
      Access-Control-Allow-Origin: "*"
  - url: /.*
    script: auto
    secure: always
